// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Admin = sequelize.define('admin', {
    createdAt: {
      type: DataTypes.BIGINT,
    },
    updatedAt: {
      type: DataTypes.BIGINT,
    },
    email: {
      type: DataTypes.STRING,
    },
    password: {
      type: DataTypes.STRING,
    },
    firstName: {
      type: DataTypes.STRING,
    },
    lastName: {
      type: DataTypes.STRING,
    },
    profileImageUrl: {
      type: DataTypes.STRING,
      field: 'profileImageURL',
    },
    emailVerified: {
      type: DataTypes.INTEGER,
    },
    isPrimaryAdmin: {
      type: DataTypes.INTEGER,
    },
    passwordChangeRequired: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'admin',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Admin.associate = (models) => {
  };

  return Admin;
};
