// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Book = sequelize.define('book', {
    createdAt: {
      type: DataTypes.BIGINT,
    },
    updatedAt: {
      type: DataTypes.BIGINT,
    },
    title: {
      type: DataTypes.STRING,
    },
    summary: {
      type: DataTypes.STRING,
    },
    authors: {
      type: DataTypes.STRING,
    },
    publisher: {
      type: DataTypes.STRING,
    },
    publishedDate: {
      type: DataTypes.STRING,
    },
    categories: {
      type: DataTypes.STRING,
    },
    coverLinks: {
      type: DataTypes.STRING,
    },
    isbn: {
      type: DataTypes.STRING,
    },
    isbnData: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'book',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Book.associate = (models) => {
    Book.belongsToMany(models.user, {
      through: models.userbook,
      otherKey: 'user',
      foreignKey: 'book'
    })
  };

  return Book;
};
