// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Conversation = sequelize.define('conversation', {
    createdAt: {
      type: DataTypes.BIGINT,
    },
    updatedAt: {
      type: DataTypes.BIGINT,
    },
    isRead: {
      type: DataTypes.INTEGER,
    },
    isInitial: {
      type: DataTypes.INTEGER,
    },
    status: {
      type: DataTypes.STRING,
    },
    readAt: {
      type: DataTypes.DOUBLE,
    },
    from: {
      type: DataTypes.INTEGER,
    },
    to: {
      type: DataTypes.INTEGER,
    },
    latestMessage: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'conversation',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Conversation.associate = (models) => {
  };

  return Conversation;
};
