// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Mangopayuser = sequelize.define('mangopayuser', {
    createdAt: {
      type: DataTypes.BIGINT,
    },
    updatedAt: {
      type: DataTypes.BIGINT,
    },
    mangopayUserId: {
      type: DataTypes.STRING,
    },
    walletIds: {
      type: DataTypes.STRING,
    },
    card: {
      type: DataTypes.STRING,
    },
    bankAccount: {
      type: DataTypes.STRING,
    },
    user: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'mangopayuser',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Mangopayuser.associate = (models) => {
  };

  return Mangopayuser;
};
