// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Message = sequelize.define('message', {
    createdAt: {
      type: DataTypes.BIGINT,
    },
    updatedAt: {
      type: DataTypes.BIGINT,
    },
    textMessage: {
      type: DataTypes.STRING,
    },
    imageUrl: {
      type: DataTypes.STRING,
      field: 'imageURL',
    },
    isRead: {
      type: DataTypes.INTEGER,
    },
    readAt: {
      type: DataTypes.DOUBLE,
    },
    conversation: {
      type: DataTypes.INTEGER,
    },
    from: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'message',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Message.associate = (models) => {
  };

  return Message;
};
