// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Transactionrating = sequelize.define('transactionrating', {
    createdAt: {
      type: DataTypes.BIGINT,
    },
    updatedAt: {
      type: DataTypes.BIGINT,
    },
    stars: {
      type: DataTypes.DOUBLE,
    },
    status: {
      type: DataTypes.STRING,
    },
    approvedAt: {
      type: DataTypes.DOUBLE,
    },
    reviewer: {
      type: DataTypes.INTEGER,
    },
    user: {
      type: DataTypes.INTEGER,
    },
    transaction: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'transactionrating',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Transactionrating.associate = (models) => {
  };

  return Transactionrating;
};
