// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Transaction = sequelize.define('transaction', {
    createdAt: {
      type: DataTypes.BIGINT,
    },
    updatedAt: {
      type: DataTypes.BIGINT,
    },
    isFor: {
      type: DataTypes.STRING,
    },
    paymentStatus: {
      type: DataTypes.STRING,
    },
    status: {
      type: DataTypes.STRING,
    },
    isAutomaticallyValidated: {
      type: DataTypes.INTEGER,
    },
    acceptedAt: {
      type: DataTypes.DOUBLE,
    },
    deliveredAt: {
      type: DataTypes.DOUBLE,
    },
    returnedAt: {
      type: DataTypes.DOUBLE,
    },
    paidAt: {
      type: DataTypes.DOUBLE,
    },
    totalOfAmounts: {
      type: DataTypes.DOUBLE,
    },
    priceOfBooks: {
      type: DataTypes.DOUBLE,
    },
    shippingNumber: {
      type: DataTypes.STRING,
    },
    deliveryInformation: {
      type: DataTypes.STRING,
    },
    feeInformation: {
      type: DataTypes.STRING,
    },
    giver: {
      type: DataTypes.INTEGER,
    },
    receiver: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'transaction',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Transaction.associate = (models) => {
  };

  return Transaction;
};
