// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Userbook = sequelize.define('userbook', {
    createdAt: {
      type: DataTypes.BIGINT,
    },
    updatedAt: {
      type: DataTypes.BIGINT,
    },
    condition: {
      type: DataTypes.STRING,
    },
    type: {
      type: DataTypes.STRING,
    },
    price: {
      type: DataTypes.DOUBLE,
    },
    isFor: {
      type: DataTypes.STRING,
    },
    isPrivate: {
      type: DataTypes.INTEGER,
    },
    status: {
      type: DataTypes.STRING,
    },
    user: {
      type: DataTypes.INTEGER,
    },
    book: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'userbook',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Userbook.associate = (models) => {
  };

  return Userbook;
};
